import React from 'react'
import { createContext, useState } from "react";

export const bucket = createContext();


function CreateStore(props) {
    const [data, setData ] = useState([
        {
            id : 1,
            heading: "Yash to take over ₹150 crore for Ramayan; to undergo transformation",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/20/550x309/Yash_Sugandha_Rawal_1697806243978_1697806244149.jpg",
            footer : "Bollywood Latest",
            cat : "Latest",
            description : "Kannada superstar Yash, who has found wide fame with the success of KGF franchise, is now eyeing entry into Bollywood, for which he has signed Nitesh Tiwari’s ambitious project Ramayana, for which he is charging over ₹150 crore. If industry buzz is to be believed, Tiwari has signed Ranbir Kapoor to essay the role of Lord Rama, Sai Pallavi as Sita and Yash as Ravana. The film will reportedly go on floors around next year in February.",
            url : "https://www.hindustantimes.com/htcity/cinema/yash-to-take-over-rs-150-crore-for-ramayan-to-undergo-transformation-101697806189547.html",
        },
        {
            id : 2,
            heading: "Shah Rukh Khan’s ‘Jawan’ Surpasses ‘Pathaan’ to Become Top Indian Film of the Year",
            image : "https://variety.com/wp-content/uploads/2023/09/Jawan.jpg?w=1000&h=563&crop=1&resize=681%2C383",
            footer : "Bollywood Latest",
            cat : "",
            description : "Shah Rukh Khan has beaten Shah Rukh Khan at the box office. The Bollywood star’s “Jawan” has sped past his own “Pathaan” to occupy the box office top spot among the Indian films of 2023. Jawan, featuring Khan in a dual role as a father and son who set out to rectify corruption in Indian society, opened on Sept. 7 and shattered the star’s own Bollywood opening day record. It now has a total of $130.3 million, according to numbers released by producer Red Chillies Entertainment, besting “Pathaan,” which opened in January and concluded its run with $126 million. In third place on the 2023 Indian box office chart, behind the two Khan vehicles, are Sunny Deol’s “Gadar 2” with $83 million, Rajinikanth’s “Jailer” with $78.2 million and Karan Johar’s “Rocky Aur Rani Kii Prem Kahaani” with $42.8 million.",
            url : "https://variety.com/2023/film/news/shah-rukh-khan-jawan-pathaan-box-office-1235741959/",
        }, 
        {
            id : 3,
            heading: "Taapsee Pannu calls 'content is king’ a myth, talks about hypocrisy in Bollywood: 'Picture mein actor kaun hai?'",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/13/550x309/taapsee_1678609741949_1697175180158.jpg",
            footer : "Bollywood Top",
            cat : "",
            description : "Taapsee Pannu has opened up about how small-budget films get affected by the ‘star system’ in Bollywood. In an interview with ETimes, the actor, who made her debut a producer with the just-released film Dhak Dhak, called out the hypocrisy that’s blatant in the film industry. She said people want to know 'who is the hero' even before they hear a line about a film. ",
            url : "https://www.hindustantimes.com/entertainment/bollywood/taapsee-pannu-calls-out-hypocrisy-in-bollywood-101697174722098.html",
        },
        {
            id : 4,
            heading: "Mission Raniganj box office collection day 7: Akshay Kumar film earns more than ₹18 crore in India in opening week",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/13/550x309/mission_raniganj__1696902532792_1697165314949.jpg",
            footer : "Bollywood Latest",
            cat : "",
            description : "Mission Raniganj box office collection day 7: Helmed by Tinu Suresh Desai, the film has been witnessing slight dips in its earnings at the domestic box office in the last few days. As per Sacnilk.com, Mission Raniganj: The Great Bharat Rescue which released last week, has so far collected just over ₹18 crore in India. The film stars Akshay Kumar and Parineeti Chopra in the lead roles. As per the report, Mission Raniganj earned ₹1.3 crore nett in India on its seventh day, as per early estimates. The film earned ₹2.8 crore on day one, ₹4.8 crore on day two, ₹5 crore on day three and ₹1.50 crore each on day four and day five. On day six the film minted ₹1.35 crore. So far, the film earned ₹18.25 crore in India. Mission Raniganj had an overall 9.26 per cent Hindi occupancy on Wednesday.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/mission-raniganj-box-office-collection-day-7-akshay-kumar-film-opening-week-101697164133289.html",
        },
        {
            id : 5,
            heading: "Amitabh Bachchan gets grand welcome from fans, is showered in flowers as he steps out on birthday.",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/11/550x309/amitabh_1697020978270_1697020978485.png",
            footer : "Bollywood Top",
            cat : "",
            description : "Veteran Amitabh Bachchan is no less than a God to his fans. To prove the same, his admirers reached the gates of his Mumbai house, Jalsa, with garlands and flowers. The actor stepped outside to greet his fans and was showered with blessings. A paparazzi video showed Amitabh Bachchan in a traditional wear as he stood on a platform. He greeted fans with folded hands and waved at everyone. He was seen thanking everyone as people wished him. Many were busy trying to capture the moment on their mobile phones. The actor's popular songs were also being played on speakers in celebration of the special day. As the video was shared online, many fans further extended their wishes.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/amitabh-bachchan-showered-by-flowers-on-his-81st-birthday-by-fans-101697019398803.html",
        },
        {
            id : 6,
            heading: "Sunny Deol as Hanuman: Gadar 2 actor reportedly in talks with Nitesh Tiwari to join Ranbir Kapoor and Yash in Ramayana",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/10/550x309/sunny_deol_1696944094114_1696944099276.jpg",
            footer : "Bollywood Latest",
            cat : "",
            description : "If there ever was a casting coup, it's this one. As per a new report by Pinkvilla, Sunny Deol is reportedly in talks to play Hanuman in Nitesh Tiwari's adaptation of Ramayana. The trilogy already stars Ranbir Kapoor as Rama, Sai Pallavi as Sita, and Yash as Ravana. The adaptation of Ramayana is being co-produced by Nitesh, Madhu Mantena, Namit Malhotra, and Allu Aravind. The report added that all four co-producers are on board with the idea of not only casting Sunny as Hanuman in the Ramayana trilogy, but also develop a spin-off on his character. In fact, it's the idea of a separate track that has piqued the interest of the actor in the project. ",
            url : "https://www.hindustantimes.com/entertainment/bollywood/sunny-deol-hanuman-gadar-2-actor-nitesh-tiwari-ramayana-ranbir-kapoor-yash-sai-pallavi-101696943637693.html",
        },
        {
            id : 7,
            heading: "Samsung, Vivo leads the top-selling smartphone chart in India",
            image : "https://images.indianexpress.com/2023/10/best-selling-phone-brands.jpg?w=640",
            footer : "Technology Latest",
            cat : "",
            description : "Samsung with a market share of 18 per cent is currently the number one smartphone brand in the country, and Vivo (including iQOO) is in the second position with a 17 per cent market share.   //  According to the latest report by the research firm Counterpoint, Samsung and Vivo are leading India’s top-selling smartphone brands in Q2 2023, with a market share of 20 per cent and 18 per cent respectively. While the overall market size has declined by 3 per cent year-on-year, 5G smartphone shipments are on the rise, with a market share of 50 per cent. // Samsung with a market share of 18 per cent is currently the number one smartphone brand in the country, and Vivo (including iQOO) is in the second position with a 17 per cent market share. Xiaomi (including Poco) slips down to the third portion but still maintains a solid market share of 15 per cent, while Realme and Oppo are in fourth and fifth position, with a market share of 12, and 11 per cent respectively.",
            url : "https://indianexpress.com/article/technology/tech-news-technology/top-smartphone-brands-q2-2023-india-8979611/",
        },
        {
            id : 8,
            heading: "OnePlus foldable phone ‘Open’ arriving on October 19: Everything you need to know",
            image : "https://images.indianexpress.com/2023/10/oneplus-foldable.jpg?w=640",
            footer : "Technology Latest",
            cat : "Latest",
            description : "OnePlus, the Chinese tech giant known for its flagship killer smartphones, is finally entering the foldable phone market with its OnePlus Open. The company has confirmed that the OnePlus Open will be launched globally on October 19, and interested customers can pre-book the device from the official website to avail benefits and offers. // The OnePlus Open is expected to be a premium device with a high-end processor, a large battery, and a dual-display design. The company is yet to confirm the specs of the phone, but there have been numerous leaks and rumours that have painted a pretty good picture of what to expect. Let’s take a look. // What’s under the hood? // The OnePlus Open is likely to be powered by the Snapdragon 8 Gen 2 SoC, which is Qualcomm’s latest flagship chipset that offers improved performance, efficiency, and connectivity. The OnePlus Open may also come with up to 16GB of LPDDR5X RAM and up to 1TB of UFS 4.0 storage, which would make it one of the most powerful foldable phones in the market.",
            url : "https://indianexpress.com/article/technology/tech-news-technology/oneplus-open-everything-to-know-specs-price-launch-8982610/",
        },
        {
            id : 9,
            heading: "New AI tool diagnoses brain tumors on the operating table",
            image : "https://images.indianexpress.com/2023/10/Brain-mri-20231012.jpg?w=640",
            footer : "Technology Latest",
            cat : "",
            description : "Scientists in the Netherlands report using artificial intelligence to arm surgeons with knowledge about the tumor that may help them make that choice. Once their scalpels reach the edge of a brain tumor, surgeons are faced with an agonizing decision: cut away some healthy brain tissue to ensure the entire tumor is removed, or give the healthy tissue a wide berth and risk leaving some of the menacing cells behind. Now scientists in the Netherlands report using artificial intelligence to arm surgeons with knowledge about the tumor that may help them make that choice. The method, described in a study published Wednesday in the journal Nature, involves a computer scanning segments of a tumor’s DNA and alighting on certain chemical modifications that can yield a detailed diagnosis of the type and even subtype of the brain tumor. That diagnosis, generated during the early stages of an hourslong surgery, can help surgeons decide how aggressively to operate, the researchers said. In the future, the method may also help steer doctors toward treatments tailored for a specific subtype of tumor.",
            url : "https://indianexpress.com/article/technology/science/ai-tool-diagnose-brain-tumour-during-operation-8980004/",
        },
        {
            id : 10,
            heading: "Chandrayaan-3 goes dark again? Former ISRO chief says ‘no hope of reviving’ Vikram lander & Pragyan rover",
            image : "https://images.indianexpress.com/2023/08/chandrayaan-3-mission-vikram-featured.jpg?w=640",
            footer : "Technology Latest",
            cat : "image right",
            description : "Former ISRO chairman, AS Kiran Kumar, has shared his thoughts on Vikram lander and Pragyan rover that were put on sleep mode in early September. After days of anticipation, now it seems there is no chance of Chandrayaan-3’s moon lander and rover waking up. According to space scientist and former ISRO chairman, AS Kiran Kumar, there is no hope of reviving India’s third lunar mission. On September 22, after a new lunar day began, ISRO stated that efforts were made to establish contact with the Vikram lander and Pragyan rover, both powered by solar energy. However, despite efforts, there have been no signals received from either the lander or the rover. It is to be noted that ISRO put the lander and rover into sleep mode on September 4 and 2, before sunset on the moon, hoping to revive it during the next sunrise around September 22. Both Vikram lander and Pragyan rover have been designed to operate for one whole lunar day which is about 14 days on Earth.",
            url : "https://indianexpress.com/article/technology/science/chandrayaan-3-goes-dark-again-vikram-lander-pragyan-rover-sleep-forever-8972159/",
        },
        {
            id : 11,
            heading: "NASA to fly rockets into October 14 solar eclipse’s shadow",
            image : "https://images.indianexpress.com/2023/10/Annular-eclipse-20231003.jpg?w=640",
            footer : "Technology Latest",
            cat : "Article",
            description : "As parts of the world get plunged into partial darkness during the October 14 annular solar eclipse, NASA will send rockets flying into the shadow of the eclipse. On October 14, people in many parts of North and South America will see the Sun dimming to about 10 per cent of its normal brightness, leaving only a bright “ring of fire” as the annular eclipse happens. But those near the White Sands Missile Range in New Mexico will also notice sudden bright streaks in the sky hurtling towards the eclipse—three rockets that NASA plans to launch.",
            url : "https://indianexpress.com/article/technology/science/nasa-rocket-solar-eclipse-shadown-october-14-8976074/",
        },
        {
            id : 12,
            heading: "How to use Google Search’s new Dall-E-like AI image generator",
            image : "https://images.indianexpress.com/2023/10/google-sge-image-generator-featured.jpg?w=640",
            footer : "Technology Latest",
            cat : "",
            description : "Google has unveiled a new feature that lets you create images from text prompts using its Search Generative Experience (SGE) tool. The feature, which is available to users who are part of Google’s Search Labs program, uses the Imagen family of AI models to generate images based on your query.  The feature is similar to Microsoft’s Bing Image Creator, which uses OpenAI’s Dall-E 3 model to create images from text prompts. Bing Image Creator was launched in March and has been popular among users who want to make their own custom images. According to Google, SGE has several safeguards to prevent the generation of harmful or inappropriate images. For example, the tool will not generate images that violate the company’s prohibited use policy for generative AI, or images that depict photorealistic faces or notable individuals. Google also says that every image generated by SGE will have metadata labelling and embedded watermarking to indicate that it was created by AI. Additionally, the tool is only available to users who are 18 or older.",
            url : "https://indianexpress.com/article/technology/artificial-intelligence/how-to-use-google-search-dall-e-like-ai-image-generator-sge-8982291/",
        },
        {
            id : 13,
            heading: "The Taste With Vir: Sri Lankan cuisine and Hoppers",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/17/550x309/Hoppers_Sri_Lanka_1697513647355_1697513651906.jpg",
            footer : "Food Latest",
            cat : "",
            description : "Indians who visit Sri Lanka for the first time usually come back saying how much it reminded them of Kerala. I am not so sure about that. Though it is a small island, Sri Lanka has such a wide variety of landscapes that it is hard to generalise. (But then Kerala has it all too; from beaches to backwaters to hills). The food can be confusing. Yes, the Sri Lankans eat dal. But they call it dal curry and add coconut milk to it. They add dried fish to many dishes, which always surprises Indians. Many decades ago, I was part of an Indian delegation to Sri Lanka. A vegetarian member of our delegation told a Lankan chef how much he had enjoyed the aubergine at lunch . What was the unusual spice he tasted in the dish? ",
            url : "https://www.hindustantimes.com/opinion/the-taste-with-vir-the-sri-lankan-cuisine-and-hoppers-101697512172152.html",
        },
        {
            id : 14,
            heading: "Conscious kitchens serve food for thought",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/16/550x309/PTCLEIYG_1697441205174_1697441224119.jpg",
            footer : "Food Latest",
            cat : "Article",
            description : "Every year, World Food Day is celebrated on October 16 to focus on saving food and water. With hunger being used as a weapon in war and conflicts, finding ways to curb is the need of the hour. Today, restaurants and hotels talk about the innovative ways they use to support zero waste management.",
            url : "https://www.hindustantimes.com/htcity/conscious-kitchens-serve-food-for-thought-101697440824064.html",
        },
        {
            id : 15,
            heading: "Kidney-friendly diet to lower your creatinine levels, promote overall kidney health",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/13/550x309/The-waiting-duration-for-kidney-transplant-at-Post_1687737915487_1697185817051.jpg",
            footer : "Food Latest",
            cat : "Stories",
            description : "Creatinine is a natural waste product produced by muscles during regular wear and tear and it exits the body through urine but in cases of impaired kidney function, it can accumulate in the blood. High creatinine level can be a sign of serious health condition but also be a temporary byproduct of certain lifestyle factors or conditions hence, any treatment or lifestyle changes undertaken for high creatinine levels should be under a guidance of healthcare provider. Creatinine is a muscle breakdown product, formed due to hydrolysis of creatine and phosphocreatine. Creatinine is endogenously produced in the human body and freely filtered by the kidneys. Therefore, serum creatinine concentration is utilized as an indirect measure of ‘kidney function’ and is the commonest biomarker used in estimation of glomerular filtration rate (eGFR)’. A normal level depends on the age, gender, race and body size (muscle mass). High creatinine levels may be a sign of kidney disease.",
            url : "https://www.hindustantimes.com/lifestyle/health/kidneyfriendly-diet-to-lower-your-creatinine-levels-promote-overall-kidney-health-101697185519262.html",
        },
        {
            id : 16,
            heading: "Taste of Life: Inter-caste ‘Sahabhojan’ marked Mahatma Gandhi’s birthday",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/04/550x309/-Jhunka-bhakar--at--Sahabhojan--was-considered-an-_1696446309254.jpg",
            footer : "Food Latest",
            cat : "",
            description : "A sahabhojan (community feast) held in Pune in 1936 showcased the dish 'jhunka-bhakar' as a symbol of breaking caste barriers and promoting equality. Pune: Food is an identity marker of caste, class, family, kinship, tribe affiliation, and gender. What we eat, with whom we eat, when, and why, is key to understanding the Indian social landscape as well as the relationships, emotions, status, and transactions of people within it.",
            url : "https://www.hindustantimes.com/cities/pune-news/taste-of-life-inter-caste-sahabhojan-marked-mahatma-gandhi-s-birthday-101696446312204.html",
        },
        {
            id : 17,
            heading: "Food trends for better health in the remaining months of 2023",
            image : "https://www.hindustantimes.com/ht-img/img/2023/09/18/550x309/joshua-coleman-8V4y-XXT3MQ-unsplash_1695017390056_1695017414691.jpg",
            footer : "",
            cat : "Article",
            description : "The food and beverages industry has witnessed a lot of change in the past few years and this change is representative of the changing consumer eating patterns where there is increased affinity for mindful eating, sustainable food patterns, convenience without compromising on nutrition and ensuring a wholesome diet. People know that choosing a healthy life today is not just for the sake of a longer journey but for the joy of living each step to its fullest and thanks to the Gen Z who have started eating mindfully and are even guiding their elders about the new healthy products in the market but the question of concern is 'Do they take the steps for living healthy life correctly?'. Health is the foundation of all we do; without it, our dreams and aspirations are but castles in the air. Embrace a healthy life, for it is the key that unlocks the door to a world of endless possibilities. The thing which every individual forgets is the power of nutrition along with a balanced diet and the power of real food. Real food is home-cooked food or whole food which is free from any preservatives and provides essential vitamins and minerals. ",
            url : "https://www.hindustantimes.com/lifestyle/health/food-trends-for-better-health-in-the-remaining-months-of-2023-101695017196410.html",
        },
        {
            id : 18,
            heading: "Food allergies and intolerances: Differences, symptoms, causes, prevention tips",
            image : "https://www.hindustantimes.com/ht-img/img/2023/09/02/550x309/_c125349c-bddf-11e5-aa4a-49b6c7b94749_1693667690365.jpg",
            footer : "Food Latest",
            cat : "",
            description : "An allergic reaction to food is seen when the immune system mistakenly reacts to an otherwise harmless substance while on the other hand, a chemical reaction within the body occurs with food intolerance upon consuming certain foods or drinks. While mild to moderate symptoms of both conditions may resemble each other occasionally, it is crucial to acknowledge that only allergies involve the immune system and can lead to severe allergic responses. It is better to have a thorough understanding of what exactly is an allergic reaction and also learn about food intolerance. Unlike food allergies, which trigger severe allergic reactions and involve the immune system, food intolerances do not cause severe allergic responses. So, allergy testing cannot identify food intolerances. Understanding what exactly food intolerance is can be complex since certain substances found in foods have been known to worsen migraines, cause skin rashes like hives, or contribute to digestive issues like irritable bowel syndrome. Hence, seek the help of an expert who can guide you regarding this matter.",
            url : "https://www.hindustantimes.com/lifestyle/health/food-allergies-and-intolerances-differences-symptoms-causes-prevention-tips-101693667377213.html",
        },
        {
            id : 19,
            heading: "10 effective tips to help your child develop good eating habits",
            image : "https://www.hindustantimes.com/ht-img/img/2023/09/08/550x309/tanaphong-toochinda-FEhFnQdLYyM-unsplash_1694175686649_1694175699259.jpg",
            footer : "Food Latest",
            cat : "Stories",
            description : "Establishing healthy eating habits in children is one of the most important responsibilities of parents. However, this is sadly neglected as most parents succumb to their children's whims and tantrums and are unable to establish this. Proper nutrition is paramount to their physical growth, cognitive development, and long-term health. Poor eating patterns in early life can follow your children into adulthood. They can lead to health problems and a complicated relationship with food. By teaching children about healthy food and eating habits when they're young, you can set them up for a lifetime of good health.1. Start early and stay consistent, 2. Be a role model, 3. Engage them in the process, 4. Avoid getting junk food at home, 5. Avoid using food as a reward or punishment, 6. Regular meal and snack times, 7. Make food fun, 8. Encourage self-regulation, 9. Educate on the benefits, 10. Stay patient and persistent.",
            url : "https://www.hindustantimes.com/lifestyle/health/10-effective-tips-to-help-your-child-develop-good-eating-habits-101694173898131.html",
        },
        {
            id : 20,
            heading: "5 offbeat mango recipes you must try this summer season",
            image : "https://www.hindustantimes.com/ht-img/img/2023/04/11/550x309/mangoes_1680945864045_1681202298504_1681202298504.jpg",
            footer : "Food Top",
            cat : "Top",
            description : "As the summer season arrives, the delectable and luscious flavor of mangoes beckons us to relish them. Mangoes hold a significant cultural significance in India and have been a part of our gastronomical landscape for centuries. While traditional mango delicacies such as mango shakes, aamras, and mango lassi are widely popular, there exist a few offbeat mango recipes that one can explore and experiment with during this season. Sarita Bazaz, Founder of The Food Affairs, shared with HT Lifestyle, some offbeat mango recipes that can be savored during the summer season. Mango Chenna Payas is a delicious Indian dessert that is perfect for satisfying your sweet cravings. To make this mouth-watering dessert, mix chenna (cottage cheese) with condensed milk, and stir until it forms a smooth mixture. Then, add in fresh mango puree, and stir it well. Garnish it with some chopped nuts, and your delightful Mango Chenna Payas is ready to relish! Serve it chilled and enjoy the burst of flavors in every bite.(Sarita Bazaz). Hand churned mango ice-cream: To make this heavenly dessert, mix heavy cream, condensed milk, and vanilla extract until smooth. Then, add fresh mango puree and mix it well. Pour the mixture into a container and freeze it for a few hours until it is set. Take it out and churn it manually to break any ice crystals. Freeze it again and serve the delicious hand-churned Mango Ice Cream, topped with fresh mango slices.(Unsplash)",
            url : "https://www.hindustantimes.com/photos/lifestyle/5-offbeat-mango-recipes-you-must-try-this-summer-season-101681202167420-4.html",
        },
        {
            id : 21,
            heading: "Healing trauma through Yoga: Add these 4 exercises to your daily fitness routine",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/pexels-matheus-bertelli-13870022_1697643683251_1697643727966.jpg",
            footer : "Fitness Latest",
            cat : "image left",
            description : "Yoga experts insist that healing trauma through Yoga is a powerful practice as with its emphasis on mindfulness and gentle physical activity, the ancient practice emerges as a valuable tool. Whether it is a natural disaster, conflict or personal tragedy, the aftermath can linger in the mind and body but Yoga steps in as a holistic approach to heal, acknowledging the interconnectedness of mental and physical well-being. In the realm of Yoga, grounding poses like Tadasana (Mountain Pose) can provide a stable foundation for those seeking stability amid chaos. The breath, a fundamental aspect of Yoga, becomes a bridge between the conscious and the subconscious, aiding in the release of pent-up emotions tied to trauma. Moving through a sequence of asanas, individuals are encouraged to explore their bodies with gentleness. Balasana (Child's Pose) invites practitioners to release tension stored in the hips and lower back – common areas where the body holds stress",
            url : "https://www.hindustantimes.com/lifestyle/health/healing-trauma-through-yoga-add-these-4-exercises-to-your-daily-fitness-routine-101697643453813.html",
        },
        {
            id : 22,
            heading: "Mindful eating and Yoga: Diet tips, exercises to support a healthy heart",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/17/550x309/toa-heftiba--TTI1k1mVAY-unsplash_1697544610442_1697544638952.jpg",
            footer : "Fitness Latest",
            cat : "Stories",
            description : "In today's fast-paced world, maintaining a heart-healthy lifestyle can be a challenge as stress, poor dietary choices and a lack of physical activity often take a toll on our cardiovascular health. However, experts believe that by combining two simple yet powerful practices—mindful eating and Yoga—you can adopt a holistic approach to support a healthy heart.",
            url : "https://www.hindustantimes.com/lifestyle/health/mindful-eating-and-yoga-diet-tips-exercises-to-support-a-healthy-heart-101697543039394.html",
        },
        {
            id : 23,
            heading: "Hrithik Roshan talks about struggles in fitness journey, shares pics; thanks Saba Azad for being ‘likeminded in action’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/17/550x309/Hrithik_Roshan_1697531791160_1697531823975.jpg",
            footer : "Fitness Latest",
            cat : "Post",
            description : "Actor Hrithik Roshan has given a glimpse of his fitness journey over the last few months. Taking to Instagram on Tuesday, Hrithik also posted several pictures showing how he transformed himself. The actor also credited his girlfriend-actor Saba Azad for helping him reach his goal. In the first picture collage, Hrithik posted a selfie of himself from August 31 and another from October 7 showing the changes in his body during the period. The next collage is of Hrithik on August 28 and another on October 7. The last photo is of the actor on August 25 and then again on October 4. He also shared three voice notes his mentor sent him.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/hrithik-roshan-struggles-in-fitness-journey-shares-transformation-pics-thanks-saba-azad-101697529589736.html",
        },
        {
            id : 24,
            heading: "Amazon Sale 2023: Looking for fitness items? Up to 82% off on cycles, dumbbells",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/Amazon_sale_sports_1697622436600_1697622436767.jpg",
            footer : "Fitness Latest",
            cat : "",
            description : "Purchasing fitness and sports items during a sale is a smart choice for several reasons. Firstly, it allows you to access quality gear at significantly reduced prices, making it more affordable to kickstart or upgrade your fitness journey. Since these products are often considered non-essentials by many Indians not actively engaged in physical activities, sales offer a unique opportunity to save on expenses that might otherwise deter participation. Mega discounts on sports equipment, workout clothing, and accessories enable more individuals to embrace a healthier lifestyle, whether for personal health goals or the sheer enjoyment of sports. Bargain hunting during sales is a win-win for both your wallet and overall well-being.",
            url : "https://www.hindustantimes.com/lifestyle/health/amazon-sale-2023-looking-for-fitness-items-up-to-82-off-on-cycles-dumbbells-101697591993494.html",
        },
        {
            id : 25,
            heading: "The Art and Science of Fitness | The power of habits in developing lasting fitness routines",
            image : "https://www.hindustantimes.com/ht-img/img/2023/09/16/550x309/cycling_1694883915626_1694883916051.jpg",
            footer : "Fitness Latest",
            cat : "",
            description : "Exactly a decade ago, I was approached by a women’s fitness magazine to coach women from all walks of life to run 6 km over a period of 3 months. I thought it was going to be a walk in the park for me as I had just come back from Ladakh after having organised the fourth edition of La Ultra - The High, an insane ultra-marathon which at that time had a distance of 222 km, involving crossing high mountain passes twice over in just 48 hours. When I had initially conceptualised this event, I was told by experts of all kinds that it was impossible and dangerous, that I could get someone killed.",
            url : "https://www.hindustantimes.com/opinion/the-art-and-science-of-fitness-the-power-of-habits-in-developing-lasting-fitness-routines-101694883333447.html",
        },
        {
            id : 26,
            heading: "Major health tips to increase the fitness of an athlete",
            image : "https://www.hindustantimes.com/ht-img/img/2023/05/02/550x309/yogendra-singh-vdK00QxPoXk-unsplash_1683039534176_1683039560615.jpg",
            footer : "Fitness Latest",
            cat : "Article",
            description : "One would think all sportsmen are incredibly fit and while that is true to a large extent, they are all prone to specific injuries depending on the respective sport as stresses of performance and competition adversely affect their health too. As per health experts, every athlete has had one or more of the below: Muscle tears and tightness Ankle sprains Knee ligament injuries Stress fractures Groin and Back pain",
            url : "https://www.hindustantimes.com/lifestyle/health/major-health-tips-to-increase-the-fitness-of-an-athlete-101683039338062.html",
        },
        {
            id : 27,
            heading: "The Art and Science of Fitness | Balance — the simple key to a healthy life",
            image : "https://images.hindustantimes.com/img/2022/11/07/550x309/standing_exercise_1643955945457_1667823307808_1667823307808.jpg",
            footer : "",
            cat : "Article",
            description : "Good balance helps you perform better in every aspect of a healthy life. Here is how you can assess your ability to maintain your body's equilibrium, and how you can improve it. Most people don’t realise that when they walk or run, they are balancing on one foot before moving to the next one. Interestingly, when we walk, there is one foot on the ground at all times, one replacing the other, but while running, with each stride, for a moment, both feet are off the ground. This is why, when we run, we need even more balance control. If you don’t have good balance, sooner than later, you are going to come tumbling down.",
            url : "https://www.hindustantimes.com/health/the-art-and-science-of-fitness-balance-the-simple-key-to-a-healthy-life-101667811535043.html",
        },
        {
            id : 28,
            heading: "The Art and Science of Fitness | Can running or exercising kill you?",
            image : "https://images.hindustantimes.com/img/2022/09/23/550x309/pti11-19-2018-000043b_8dfbb9d4-2ae4-11eb-b5c7-b29fb991c478_1663936656514_1663936656514.jpg",
            footer : "Fitness Top",
            cat : "Top",
            description : "Do people, on rare occasions, die while exercising or running? Yes. Is that cause for worry? No. Doctors, professors, and yours truly tell you why: On a pleasant morning in Bengaluru in May 2008, when running hadn’t yet become popular, a lean man in his mid-30s collapsed at around the 4 km mark of a 10 km race. Fortunately, the critical care ambulance was stationed right there, manned by the best emergency medicine doctor in the team covering the event, of which I was the medical director.",
            url : "https://www.hindustantimes.com/health/the-art-and-science-of-fitness-can-running-or-exercising-kill-you-101663934058117.html",
        },
        {
            id : 29,
            heading: "Fitness alert: Here's what you should know before taking a supplement",
            image : "https://www.hindustantimes.com/ht-img/img/2023/02/22/550x309/pexels-pixabay-208518_1677050172097_1677050198460_1677050198460.jpg",
            footer : "Fitness Top",
            cat : "Latest",
            description : "There is so much buzz about the potential health advantages of supplements that it can be difficult to distinguish between reality and fiction but taking a supplement when not required or in excess may lead one to the hospital. Here's what you should know before taking a supplement. For many people, living a healthy lifestyle entails more than just eating a nutritious meal and getting adequate exercise; it also includes vitamins, supplements and additional nutritional items. However, despite widespread myth in people regards their potential advantages, there is less understanding of their potential adverse effects. There is so much buzz about their potential advantages that it can be difficult to distinguish between reality and fiction as we all know that vitamins and minerals are vital for health. Further, they are optimally available in a balanced meal and can be generated in our body with optimal exercises and right exposure to sunlight.",
            url : "https://www.hindustantimes.com/lifestyle/health/fitness-alert-here-s-what-you-should-know-before-taking-a-supplement-101677048742976.html",
        },
        {
            id : 30,
            heading: "Health experts bust fitness myths that almost everyone believes",
            image : "https://images.hindustantimes.com/img/2022/01/30/550x309/mr-lee-f4RBYsY2hxA-unsplash_1643517892728_1643517912118.jpg",
            footer : "Fitness Top",
            cat : "",
            description : "Does a glass of detox water makes one loose weight? Is ‘no pain, no gain’ really true? Should you work out early morning on an empty stomach? A cup of kadha keeps away all ailments? Health experts answer these and more to bust common fitness misconceptions. At a time when everyone is prioritising their health and wellness like never before, courtesy the third year of Covid-19 pandemic, many are casually passing exercise tips which are further passed on to several folks, making it easy to fall into the trap of fitness misconceptions. It is important to ensure that your workouts are safe and effective by learning to distinguish fitness facts from many that are myths or really fiction. In the current scenario of fitness myths and half-truths, working out may sometimes lead to injury and the misconceptions about exercise or exercising ways and routine may be keeping you and your family from getting the best and safest workout. Sweat not as we got you sorted by getting some fitness experts on board to bust myths that almost everyone believes in but are far from reality.  ",
            url : "https://www.hindustantimes.com/lifestyle/health/health-experts-bust-fitness-myths-that-almost-everyone-believes-101643517543746.html",
        },
        {
            id : 31,
            heading: "Amazon Great Indian Festival Sale 2023: Up to 71% off on coffee makers",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/19/550x309/pexels-karine-monteiro-2147683_1697728120971_1697728133121.jpg",
            footer : "Technology Top",
            cat : "Post",
            description : "Embracing the thrill of savings, the Amazon Great Indian Festival Sale 2023 unfurls its digital aisles, inviting shoppers into a world of unparalleled discounts and unmatched offers. This annual extravaganza isn't merely a sale; it's a celebration of smart shopping, a carnival where savvy buyers secure their dream products without emptying their pockets. The benefits of this grand event are multifaceted, catering to the diverse needs of consumers. From cutting-edge electronics to chic fashion, every coveted item finds its price slashed. This sale, a beacon of frugality, is not just an event but a lifeline for those who seek quality at an affordable cost. For buyers with a discerning eye, products like cutting-edge gadgets, fashionable attire, and innovative kitchen appliances beckon; all waiting to be plucked at prices that redefine affordability. In the heart of every bustling household, the humble coffee maker stands tall as a necessity, transforming bleary-eyed mornings into vibrant beginnings. The aroma of freshly brewed coffee wafting through the air is an everyday luxury, a ritual that brings comfort and energy. Amidst the variety of coffee makers available, from classic drip brewers to sophisticated espresso machines, there lies a world of technology designed to elevate the coffee experience. Buyers, with an eye on the future of home brewing, should watch out for innovations like smart connectivity, precision temperature control, and eco-friendly features.",
            url : "https://www.hindustantimes.com/technology/amazon-great-indian-festival-sale-2023-up-to-71-off-on-coffee-makers-101697723666234.html",
        },
        {
            id : 32,
            heading: "Timothee Chalamet reveals Tom Cruise sent him ‘most wonderfully inspiring email’ after Dune. Here's what he said",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/tom_tim_1697627213831_1697627225350.jpg",
            footer : "Hollywood Latest",
            cat : "",
            description : "We'd love to watch Tom Cruise and Timothee Chalamet in a film together. Especially after the Dune star's revelations about the Top Gun star in a recent GQ interview. Timothee opened up on the contents of an email Tom sent to him after Dune and how he watched Top Gun: Maverick eight times in a theatre. He basically said, in Old Hollywood, you would be getting dance training and fight training, and nobody is going to hold you to that standard today. So it’s up to you. The email was really like a war cry, n the same interview, Timothee revealed that he's a huge fan of Tom. So much so that he saw his airplane thriller Top Gun: Maverick eight times, while shooting for Dune: Part Two. He even booked an entire cinema hall for a crew screening.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/timothee-chalamet-tom-cruise-sent-him-most-wonderfully-inspiring-email-after-dune-top-gun-101697626926110.html",
        },
        {
            id : 33,
            heading: "Oppenheimer is set for ‘home’ release with three-hour special features, here's all you need to know",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/Cillian-Murphy-in-and-as-Oppenheimer---Universal-P_1691595082744_1697608368264.jpg",
            footer : "Hollywood Latest",
            cat : "",
            description : "Special features included in 'Oppenheimer' home release: making-of documentary, personal stories, cast interviews, production design, music collaboration. As Christopher Nolan's monumental biopic, Oppenheimer, nears the billion-dollar mark at the global box office, Universal has unveiled the film's home release date, featuring an extensive three-hour special features package.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/oppenheimer-is-set-for-home-release-with-three-hour-special-features-heres-all-you-need-to-know-101697606146152.html",
        },
        {
            id : 34,
            heading: "Notting Hill, Love Actually, Bridget Jones writer admits lack of diversity: ‘I wouldn’t know how to write those parts'",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/8c3cd1c4-421b-11ec-ad0c-dd2840806c5c_1636811028519_1697635872471.jpg",
            footer : "Hollywood Latest",
            cat : "Top",
            description : "Richard Curtis, who wrote Notting Hill and Bridget Jones, and directed Love Actually, admitted the lack of diversity and fat-shaming in those popular rom-coms. Richard Curtis, the screenwriter of popular romantic comedies like Notting Hill (1999), Bridget Jones' Diary (2001), and Love Actually (2003), has confessed to the lack of diversity in all the films, and the fat-shaming in his directorial debut Love Actually. He recently addressed the same at the Times and Sunday Times Cheltenham Literature Festival, as reported by Today.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/notting-hill-love-actually-bridget-jones-writer-richard-curtis-admits-lack-of-diversity-101697635479855.html",
        },
        {
            id : 35,
            heading: "Past Lives review: A classic for this life and those yet to come",
            image : "https://www.hindustantimes.com/ht-img/img/2023/07/06/550x309/-p--i-Past-Lives--i--review--A-classic-for-this-li_1688676644527.jpg",
            footer : "Hollywood Latest",
            cat : "Article",
            description : "What connects Korean-Canadian director Celine Song’s highly anticipated love triangle and cinema lovers aching for some brilliant nostalgia-soaked romance? 8,000 layers of inyeon. For every film occupying the corners of my mind, there’s one iconic shot that stays with me long after the former has slowly burned itself onto my consciousness. For Past Lives, however, I was left clutching at an endless carousel of memorable frames. And then, I settled on the final scene, a quiet, simmering tearjerker that I would like to keep in the same memory box as Kapurush (1965), Satyajit Ray’s lesser-discussed film about past lovers getting reacquainted and finding themselves in a fraught present, and Before Sunrise (1995), Richard Linklater’s cult heartbreaker. For a film that’s so fraught with possibilities for romance and is yet so emotionally mature, it almost feels like a superhuman debut for director Celine Song. It tells the story of Nora, an aspiring Korean American playwright engaged at a writers’ residency in New York City. One day, on a whim, the 24-year-old runs a social media search for a cherished childhood companion in Seoul, her ‘home’ that she emigrated out of, twelve years ago. Back home, the boyfriend, named Hae Sung, has made similar efforts, and in no time, the two find each other via Facebook. As the long-lost friends reconnect over endless video calls, she plunges into feverish melancholia. What transpires over the course of the next twelve years, in a superbly executed time leap, forms the rest of the film.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/past-lives-a-meditative-love-story-of-nostalgia-longing-and-choices-between-two-worlds-101688676652099.html",
        },
        {
            id : 36,
            heading: "Hollywood returns to work soon as strike ends, get ready for these new movies, but TV shows may take time",
            image : "https://www.hindustantimes.com/ht-img/img/2023/09/25/550x309/Movie_2023-2024_1695637932932_1695637933115.jpeg",
            footer : "Hollywood Latest",
            cat : "",
            description : "Months long stalemate between the Screen Actors Guild (SAG) and the Writers Guild is set to finally end after a tentative three-year contract agreement will be approved by the Writers Guild of America's board and members. The labour dispute that had been ongoing since May 2, with writers taking to the picket lines in demand of fair compensation and better conditions. The strike had led to uncertainty over major projects that were bound to hit the theatre, and now the world of Hollywood is going to make a comeback like never before. The long-awaited moment is gradually coming to an end, and fans are thrilled for this list of web series and movies to hit the screen. If you haven't planned what your binge-watching nights in the coming days are going to look like, worry no more. However, there is still no deal between Hollywood actors and the studios. 160,000-member SAG-AFTRA has also been on strike since July alongside the writers. If the actors follow suit and reach a speedy settlement, production on scripted TV shows could begin in a matter of weeks and new episodes could be ready to air by early next year.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/hollywood-returns-to-work-and-so-will-your-favourite-tv-shows-and-movies-101695634677173.html",
        },
        {
            id : 37,
            heading: "End of strike: Hollywood goes back to work",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/03/550x309/Mission_Impossible_1696326299403_1696326299592.jpg",
            footer : "Hollywood Latest",
            cat : "",
            description : "After over 148 days, the Writers Guild of America has decided to end its strike. As a result, Hollywood studios are gearing up to get the ball rolling. It’s a light, camera action moment in Hollywood with the writers’ strike getting over. After over 148 days, leaders of the Writers Guild of America have unanimously voted to lift the strike, following which writers will be allowed to return to work. Now, Hollywood studios are gearing up to get production rolling again.Star Trek: Strange New Worlds is ready to engage. Director Chris Fisher has revealed that the production on season three will begin shortly after the disputes end, adding that he has storyboarded for the entire first episode ready too.The third season of the comedy got stuck due to the strike. Earlier this year, Sheryl Lee Ralph toldTODAY.com the writers’ room of the hit comedy was closed for business. Now, the things are ready to roll for the show.",
            url : "https://www.hindustantimes.com/htcity/cinema/end-of-strike-hollywood-goes-back-to-work-101696326132449.html",
        },
        {
            id : 38,
            heading: "Jada Pinkett Smith won't divorce Will Smith: ‘I’m not giving up on that dude, he’s not giving up on me’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/People-Jada-Pinkett-Smith-Will-Smith-0_1697594023074_1697594063325.jpg",
            footer : "",
            cat : "",
            description : "Ever since the Oscars, it’s so interesting how such an intense event can bring you closer together, and I would say that after that, we really dove in and dug in and got to this beautiful place we are now. The actor, who first revealed the bombshell news to NBC’s Hoda Kotb last week, details her much-gossiped about marriage throughout the biography. Through the years, the couple has faced rumors — of having an open marriage, a swinging lifestyle and questions about their sexual orientations — all while wearing smiles, seemingly portraying a picture-perfect life. The daytime Emmy award winner briefly thought about scrapping the project; she started writing the 400-plus page book, co-written with Mim Eichler Rivas, at the top of 2022. But after Will infamously slapped Chris Rock in real time during the Oscars over a joke about her shaved head, Pinkett Smith wondered if writing a book was the right choice.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/jada-pinkett-smith-wont-divorce-will-smith-i-m-not-giving-up-on-that-dude-he-s-not-giving-up-on-me-101697593528799.html",
        },
        {
            id : 39,
            heading: "The Canadian Lad reviews Jawan, shares 3 things Marvel can learn from the film: ‘This is missing in Hollywood’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/07/550x309/jawan_1696691695174_1696691695364.jpeg",
            footer : "Hollywood Top",
            cat : "",
            description : "Shah Rukh Khan's Jawan has earned praise from all across the globe and joining in among its admirers is YouTuber The Canadian Lad. For the first time, the film critic shared a review of Jawan and even shred three things which Hollywood, especially Marvel can learn from the film. He praised all from his female characters, action scenes to its title track in the video. Some of the action scenes in the movie are unlike anything I have seen before. What's really great is that it has strong female characters without making the male character look bad. This is something missing in Hollywood right now, especially in Marvel movies where they try to create strong female characters but often don't succeed. But Jawan is a great example of how to balance both aspects.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/the-canadian-lad-reviews-jawan-shares-3-things-marvel-can-learn-from-the-film-this-is-missing-in-hollywood-101696690129057.html",
        },
        {
            id : 40,
            heading: "Tom Holland says the entertainment business scares him: ‘I really do not like Hollywood, it is not for me’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/07/12/550x309/Tom_Holland_1640588194511_1689168552149.jpg",
            footer : "Hollywood Top",
            cat : "",
            description : "Tom Holland is making his stance clear about being an actor in Hollywood. The Spider-Man: No Way Home star opened up in a new interview that even though he is a massive fan of making movies, the entertainment industry is not for him. The 27 year-old opened up about the film business after announcing a few weeks earlier that he is taking a break from acting after making the Apple TV+ series, The Crowded Room. He plays a character which is loosely based on Billy Milligan, a US man who claimed to have 24 alternate personalities. Tom said that he was unable to switch the character off, and wanted just to be rid of him.",
            url : "https://www.hindustantimes.com/entertainment/hollywood/tom-holland-says-the-entertainment-business-scares-him-101689168268268.html",
        },
        {
            id : 41,
            heading: "‘Garbage on a platter’: Chocolate loaded omelette irks netizens",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/19/550x309/chocolate_omelette_1697709061211_1697709067270.png",
            footer : "Food Top",
            cat : "Article",
            description : "Omelettes are a highly preferred food option. One can have it for breakfast or whenever the hunger strikes. While many prefer to add vegetables or cheese to their omelettes, would you ever think of adding chocolate? Sounds bizarre, right? Well, a street food vendor was seen making a chocolate omelette, and needless to say, it irked many people. This video was shared by Gagandeep Singh on Instagram. It opens to show a man adding butter to a hot pan and breaking five eggs into it. Then he adds green chillies, onions, and tomatoes. Then he takes two chocolates and grates them on top of the omelette. Once it is ready, he pours more chocolate over it and serves it with a touch of mayonnaise.",
            url : "https://www.hindustantimes.com/trending/garbage-on-a-platter-chocolate-loaded-omelette-irks-netizens-101697708766627.html",
        },
        {
            id : 42,
            heading: "Internet disagrees with woman who branded poha the ‘absolute worst food’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/internet-poha-absolute-worst-food-viral_1697647525999_1697647533441.jpg",
            footer : "Food Top",
            cat : "",
            description : "Poha is a comfort food for many. Not only is it easy to prepare, but it is also filling in nature. Many people love to have poha for breakfast with either tea or coffee. Its preparation also varies, depending on the individual preferences. Now, a woman’s post on this popular breakfast dish has elicited reactions from people. In her post, the woman termed poha as the ‘absolute worst food’ she has ever had.",
            url : "https://www.hindustantimes.com/trending/internet-disagrees-with-woman-who-branded-poha-the-absolute-worst-food-101697647012049.html",
        },
        {
            id : 43,
            heading: "‘He's changed my life’: Gwen Stefani talks about Blake Shelton after receiving Hollywood Walk of Fame star",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/21/550x309/us-italy-diplomacy_f176ba7a-c69f-11e6-ad67-c7f41c1c9a76_1697869665526.jpg",
            footer : "Hollywood Top",
            cat : "",
            description : "Gwen Stefani received a star on the Hollywood Walk of Fame on Thursday, October 19. In her honour, her husband Blake Shelton gave an emotional speech, recalling the time they first met. Recently, in an interview with People, Stefani got candid about her family life, children, her relationship with Shelton, and how she juggles all this alongside her fame. The American singer-songwriter, 54, married the country singer, 47, in 2021. When I was young, I'd walk home from school and see my mom in her shorts doing her gardening, and my dad would be cutting the trees and make me pick up the branches. I'd be like, 'I'm never having a tree at my house.'” She calls herself a “garden flower nerd.” “When we get to Oklahoma, we're constantly working — and it's a different kind of work. It's probably what my mom was doing back in the day, and now I get it!",
            url : "https://www.hindustantimes.com/entertainment/hollywood/-hes-changed-my-life-gwen-stefani-talks-about-blake-shelton-after-receiving-hollywood-walk-of-fame-star-101697863137449.html",
        },
        {
            id : 44,
            heading: "Oppo tries to flip away foldable pain points with the Find N3 Flip",
            image : "https://images.indianexpress.com/2023/10/oppo-find-n3-flip-review-featured.jpg?w=640",
            footer : "Technology Top",
            cat : "Post",
            description : "Oppo was quick to enter the foldable race with the Find N series. Now, it has come to a point in the development of this form factor where it wants to solve the pain points associated with foldables. And that seems to be the focus of the Find N3 Flip, its new clamshell-type foldable. The Find N3 Flip tries to do three things other foldables haven’t. One, it tries to make the cover screen much more effective by literally making it a miniature version of everything the phone can do. Two, it tries to bring in a three-camera system with a 50MP primary camera, 48MP ultra-wide and 32MP portrait camera. And finally, it tries to pack in a larger 4300mAh battery, much larger than any on a flip format phone so far. But does all this make the Find N3 Flip the best flip phone out there?",
            url : "https://indianexpress.com/article/technology/tech-news-technology/oppo-find-n3-flip-review-8980273/",
        },
        {
            id : 45,
            heading: "Apple’s next-gen HomePod reported to feature an LCD screen",
            image : "https://images.indianexpress.com/2023/10/homepod-prototype.jpg?w=640",
            footer : "Technology Top",
            cat : "Article",
            description : "Apple introduced updated HomePod and HomePod mini models just a few months ago and new HomePods aren’t expected for at least a year, but a new report sheds some light on the HomePod prototype that reportedly includes a large LCD screen on the top. A photo of a HomePod prototype, which has surfaced on the web, suggests that the next-generation HomePod will feature a coloured LCD screen. The image is from an X user known as Kosutami, who is recognised for collecting Apple prototype devices. According to the picture, the top portion of the HomePod now has a larger touch area, and the device carries a code name “B720.” Kosutami claims that Apple is actively working on this prototype and that it’s in an advanced stage of development.",
            url : "https://indianexpress.com/article/technology/tech-news-technology/apples-next-gen-homepod-reported-to-feature-an-lcd-screen-8994461/",
        },
        {
            id : 46,
            heading: "",
            image : "",
            footer : "",
            cat : "",
            description : "",
            url : "",
        },
        {
            id : 47,
            heading: "",
            image : "",
            footer : "",
            cat : "",
            description : "",
            url : "",
        },
        {
            id : 48,
            heading: "",
            image : "",
            footer : "",
            cat : "",
            description : "",
            url : "",
        },
        {
            id : 49,
            heading: "",
            image : "",
            footer : "",
            cat : "",
            description : "",
            url : "",
        },
        {
            id : 50,
            heading: "Ganapath box office collection day 2: Tiger Shroff, Kriti Sanon's action film shows drop, collects ₹4.75 crore total",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/22/550x309/ganapath_box_office_1697941161846_1697941162007.jpg",
            footer : "Bollywood Latest",
            cat : "",
            description : "Ganapath box office collection: Tiger Shroff, Amitabh Bachchan and Kriti Sanon's action film showed a slight decline on Saturday as the film released in theatres ahead of an extended weekend. The film collected ₹2.25 crore on day two as per early estimates stated in a tweet by the official page of Sacnilk.com. This takes the film's 2-day total to ₹4.75 crore. The film boasts of action and a futuristic theme. The Vikas Bahl directorial had opened in theatres on Friday at ₹2.5 crore but showed no promise on its first Saturday. More tweets from the portal's X handle suggest that the film recorded occupancy at around 10 percent on Saturday.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/ganapath-box-office-collection-day-2-tiger-shroff-kriti-sanons-action-film-shows-drop-101697939907535.html",
        },
        {
            id : 51,
            heading: "The Canadian Lad reviews Jawan, shares 3 things Marvel can learn from the film: ‘This is missing in Hollywood’",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/07/550x309/jawan_1696691695174_1696691695364.jpeg",
            footer : "Bollywood Latest",
            cat : "",
            description : "Shah Rukh Khan's Jawan has earned praise from all across the globe and joining in among its admirers is YouTuber The Canadian Lad. For the first time, the film critic shared a review of Jawan and even shred three things which Hollywood, especially Marvel can learn from the film. He praised all from his female characters, action scenes to its title track in the video. Some of the action scenes in the movie are unlike anything I have seen before. What's really great is that it has strong female characters without making the male character look bad. This is something missing in Hollywood right now, especially in Marvel movies where they try to create strong female characters but often don't succeed. But Jawan is a great example of how to balance both aspects.",
            url : "https://www.hindustantimes.com/entertainment/bollywood/the-canadian-lad-reviews-jawan-shares-3-things-marvel-can-learn-from-the-film-this-is-missing-in-hollywood-101696690129057.html",
        },
        {
            id : 52,
            heading: "Sam Bahadur teaser: Vicky Kaushal is the perfect Sam Manekshaw as he challenges Indira Gandhi's ideas. ",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/13/550x309/sam_1697183705280_1697183734060.jpg",
            footer : "",
            cat : "image right",
            description : "Vishal Kaushal is back in the Indian Army uniform. No, it's not for the sequel for his 2019 military action blockbuster Uri: The Surgical Strike, for which he won a National Film Award. This time, it's a biopic of Field Marshal Sam Manekshaw, also known as Sam Bahadur. The film's teaser, released on Friday, shows Vicky transform into India's first field marshal. ",
            url : "https://www.hindustantimes.com/entertainment/bollywood/sam-bahadur-teaser-vicky-kaushal-army-movie-meghna-gulzar-strong-uri-hangover-watch-101697182387998.html",
        },
        {
            id : 53,
            heading: "Leke Prabhu Ka Naam teaser: Salman Khan and Katrina Kaif show sizzling chemistry in Tiger 3 song. Watch",
            image : "https://www.hindustantimes.com/ht-img/img/2023/10/20/550x309/salman_tiger_3_1697782974571_1697782986538.png",
            footer : "Bollywood Top",
            cat : "",
            description : "Tiger 3 song Leke Prabhu Ka Naam: YRF teased fans with a glimpse of the first song from the film featuring Salman Khan and Katrina Kaif. The teaser for Salman Khan and Katrina Kaif's song Leke Prabhu Ka Naam from their spy film Tiger 3 has been unveiled. Sharing it on YouTube on Friday, the makers Yash Raj Films (YRF) ",
            url : "https://www.hindustantimes.com/entertainment/bollywood/leke-prabhu-ka-naam-tiger-song-teaser-salman-khan-katrina-kaif-chemistry-101697782862474.html",
        },
        
    ])
  return (
    <>
        <bucket.Provider value={[data , setData]}>  
            {props.children}
        </bucket.Provider>
    
    </>
  )
}

export default CreateStore;